variable "hostname" {
  description = "Primary hostname to create DNS record for this app"
  type        = string
}

variable "hostname_blue" {
  description = "Optional blue hostname for testing the app"
  type        = string
  default     = ""
}

variable "hostname_create" {
  description = "Whether to create Route53 records in the hosted zone"
  type        = bool
  default     = true
}

variable "hosted_zone" {
  description = "Existing Hosted Zone domain to add hostnames as DNS records (e.g. example.com.)"
  type        = string
}

variable "hostname_redirects" {
  description = "Comma-separated hostnames to redirect to the main one"
  type        = string
  default     = ""
}

variable "alb_cloudfront_key" {
  description = "Key generated by terraform-aws-ecs module to allow ALB connection from CloudFront"
  type        = string
}

variable "alb_dns_name" {
  description = "ALB DNS Name that CloudFront will point to as origin"
  type        = string
}

variable "certificate_arn" {
  description = "ACM certificate ARN in us-east-1 for this app to use in CloudFront (should cover hostname and any aliases)"
  type        = string
}

variable "cloudfront_web_acl_id" {
  description = "Optional WAFv2 Web ACL ID to attach to CloudFront (leave empty for none)"
  type        = string
  default     = ""
}

variable "cloudfront_forward_headers" {
  description = "Headers to forward to the origin from CloudFront"
  type        = list(string)
  default     = ["*"]
}
